postgres.connection.endpoint=jdbc:postgresql://localhost:5432/postgres
postgres.connection.user=postgres
postgres.connection.password=postgres
postgres.database.schema=user_schema
postgres.database.table=user_info
